/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package parse;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTSTATEMENTSTRING = 2;
  public int JJTISSTATEMENT = 3;
  public int JJTSTATEMENT = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTDECLARESTATEMENT = 6;
  public int JJTID = 7;
  public int JJTIFSTATEMENT = 8;
  public int JJTWHILESTATEMENT = 9;
  public int JJTCONDITION = 10;
  public int JJTFORSTATEMENT = 11;
  public int JJTFORFIRST = 12;
  public int JJTFORSECOND = 13;
  public int JJTFORTHIRD = 14;
  public int JJTEXPRESSION = 15;
  public int JJTTERM = 16;
  public int JJTUNARY = 17;
  public int JJTELEMENT = 18;
  public int JJTVAR = 19;
  public int JJTARRAY = 20;
  public int JJTKONG = 21;
  public int JJTLIST = 22;


  public String[] jjtNodeName = {
    "start",
    "block",
    "statementstring",
    "isstatement",
    "statement",
    "assignment",
    "DeclareStatement",
    "id",
    "IfStatement",
    "WhileStatement",
    "Condition",
    "ForStatement",
    "ForFirst",
    "ForSecond",
    "ForThird",
    "Expression",
    "Term",
    "unary",
    "element",
    "var",
    "array",
    "kong",
    "List",
  };
}
/* JavaCC - OriginalChecksum=1314b61dfc26f79aa804fcc898fe75e6 (do not edit this line) */
