/* Generated By:JavaCC: Do not edit this line. YFFXTreeConstants.java Version 5.0 */
package yffx;

public interface YFFXTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTSTATEMENTBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSEQUENCESTATEMENT = 4;
  public int JJTDECLARATIVESTATEMENT = 5;
  public int JJTASSIGNMENTSTATEMENT = 6;
  public int JJTCONDITIONALSTATEMENT = 7;
  public int JJTCIRCULARSTATEMENT = 8;
  public int JJTCONDITION = 9;
  public int JJTEXPRESSION = 10;
  public int JJTADDITIVEEXPRESSION = 11;
  public int JJTMULTIPLICATIVEEXPRESSION = 12;
  public int JJTUNARYEXPRESSION = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTINTEGER = 15;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "StatementBlock",
    "Statement",
    "SequenceStatement",
    "DeclarativeStatement",
    "AssignmentStatement",
    "ConditionalStatement",
    "CircularStatement",
    "Condition",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=b1217ac0b27e0c9a42f9fb5ff66add4f (do not edit this line) */
