/* Generated By:JJTree&JavaCC: Do not edit this line. YFFXConstants.java */
package yffx;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface YFFXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int NUM = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int MAIN = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int DOUBLE = 18;
  /** RegularExpression Id. */
  int FLOAT = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int RELATION = 23;
  /** RegularExpression Id. */
  int GREAT = 24;
  /** RegularExpression Id. */
  int LOWER = 25;
  /** RegularExpression Id. */
  int GREATE = 26;
  /** RegularExpression Id. */
  int LOWERW = 27;
  /** RegularExpression Id. */
  int EQUAL = 28;
  /** RegularExpression Id. */
  int UNEQUAL = 29;
  /** RegularExpression Id. */
  int LC = 30;
  /** RegularExpression Id. */
  int RC = 31;
  /** RegularExpression Id. */
  int LM = 32;
  /** RegularExpression Id. */
  int RM = 33;
  /** RegularExpression Id. */
  int LB = 34;
  /** RegularExpression Id. */
  int RB = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<NUM>",
    "<DIGIT>",
    "\"main\"",
    "\"void\"",
    "\"while\"",
    "\"=\"",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"double\"",
    "\"float\"",
    "\"do\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<RELATION>",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"%\"",
  };

}
